### ISSUE TITLE
Checklist for the first final version of the specification

### ISSUE THREAD

**Issue by wks** [microvm/microvm-meta#41]
- [X] HAIL #29 
- [X] Unsafe native interface. #24 
- [X] API in C (header)
- [X] API in C (documented)
- [X] API as Mu instructions (common instructions). #36 
- [X] Adjust the undefined function API
