### ISSUE TITLE
Next milestone

### ISSUE THREAD

**Issue by wks** [microvm/microvm-meta#8]
As we already found many problems in the current µVM design, many changes can be done to improve it. Here is a list of issues to be addressed in the next µVM specification.
- [X] #6 #10  : More instructions can result in abnormal control flows. This should be reflected in the instruction set.
  - Stick to the standard control flow graph, not factored control flow graph.
- [X] #4 : Use C++11 memory model.
- [X] #7 : Update the swap-stack API.
- [X] #5 : Update the OSR API.
- [X] #9 : Support vector instructions.
- [X] Provide mechanisms (futex) to support blocking locks and other thread synchronisation primitives.

In case there are someone who wants to play with the reference implementation, the current implementation will be branched and the current specification will be forked into another repository.
